from __future__ import annotations

import re
from datetime import datetime, timedelta
from typing import Any

from kubectl_explain_failure.causality import CausalChain, Cause
from kubectl_explain_failure.rules.base_rule import FailureRule
from kubectl_explain_failure.timeline import Timeline, parse_time


class ExternalSecretsSyncFailureRule(FailureRule):
    """
    Detects Pods blocked by External Secrets Operator, Vault, or Secrets Store
    CSI sync failures.

    Real-world behavior:
    - production workloads often reference Kubernetes Secrets generated by
      ExternalSecret controllers, Vault Agent/CSI integrations, or cloud secret
      providers
    - the Pod symptom is usually mundane: missing Secret, missing key,
      CreateContainerConfigError, or FailedMount
    - the real root cause is upstream sync failure: provider auth, SecretStore
      readiness, Vault path/permission, cloud API access, or CSI provider mount
      errors before the Kubernetes Secret becomes available
    """

    name = "ExternalSecretsSyncFailure"
    category = "Compound"
    severity = "High"
    priority = 76
    deterministic = True

    phases = ["Pending", "Running"]
    requires = {
        "pod": True,
        "context": ["timeline"],
        "optional_objects": [
            "externalsecret",
            "secretstore",
            "clustersecretstore",
            "secretproviderclass",
            "secretproviderclasspodstatus",
            "secret",
        ],
    }

    blocks = [
        "SecretNotFound",
        "SecretKeyMissing",
        "ConfigDependencyMissingChain",
        "ContainerCreateConfigError",
        "FailedMount",
        "CrashLoopBackOff",
        "RepeatedCrashLoop",
    ]

    WINDOW_MINUTES = 30
    MAX_SYNC_TO_POD_GAP = timedelta(minutes=15)
    MIN_SYNC_FAILURE_OCCURRENCES = 1
    CACHE_KEY = "_external_secrets_sync_failure_candidate"

    EXTERNAL_SECRET_EVENT_MARKERS = (
        "externalsecret",
        "external secret",
        "external-secrets",
        "external-secrets.io",
        "secretstore",
        "clustersecretstore",
        "secret provider class",
        "secretproviderclass",
        "secrets-store.csi.k8s.io",
        "secrets-store-csi-driver",
        "vault",
        "aws secrets manager",
        "azure key vault",
        "gcp secret manager",
        "google secret manager",
        "provider",
        "csi-secrets-store",
    )

    SYNC_FAILURE_MARKERS = (
        "sync failed",
        "secret sync failed",
        "failed to sync",
        "failed to refresh",
        "failed to fetch",
        "failed to get secret",
        "failed to get external secret",
        "could not get secret",
        "provider error",
        "secretstore not ready",
        "store not ready",
        "access denied",
        "permission denied",
        "forbidden",
        "unauthorized",
        "invalid provider config",
        "no such secret",
        "secret not found",
        "vault",
        "context deadline exceeded",
        "timed out",
        "timeout",
        "throttl",
        "rate exceeded",
        "invalid client",
        "token expired",
    )

    POD_SECRET_FAILURE_MARKERS = (
        "secret",
        "couldn't find key",
        "not found",
        "failedmount",
        "failed mount",
        "failed to setup volume",
        "mountvolume.setup failed",
        "createcontainerconfigerror",
        "references non-existent secret key",
        "secretproviderclass",
        "secrets-store.csi.k8s.io",
        "failed to mount secrets store objects",
    )

    STARTUP_BLOCK_REASONS = {
        "CreateContainerConfigError",
        "FailedMount",
        "Failed",
        "Warning",
    }

    SECRET_NOT_FOUND_RE = re.compile(r'secret "([^"]+)" not found', re.IGNORECASE)
    SECRET_KEY_RE = re.compile(
        r'couldn\'t find key "?([^"\s]+)"? in Secret (?:(?:[^/\s]+)/)?([^\s",]+)',
        re.IGNORECASE,
    )
    NONEXISTENT_SECRET_KEY_RE = re.compile(
        r"references non-existent secret key:\s*([^\s\",]+)",
        re.IGNORECASE,
    )

    def _parse_timestamp(self, raw: Any) -> datetime | None:
        if not isinstance(raw, str):
            return None
        try:
            return parse_time(raw)
        except Exception:
            return None

    def _event_time(self, event: dict[str, Any]) -> datetime | None:
        return (
            self._parse_timestamp(event.get("firstTimestamp"))
            or self._parse_timestamp(event.get("eventTime"))
            or self._parse_timestamp(event.get("lastTimestamp"))
            or self._parse_timestamp(event.get("timestamp"))
        )

    def _event_end(self, event: dict[str, Any]) -> datetime | None:
        return (
            self._parse_timestamp(event.get("lastTimestamp"))
            or self._parse_timestamp(event.get("eventTime"))
            or self._parse_timestamp(event.get("firstTimestamp"))
            or self._parse_timestamp(event.get("timestamp"))
        )

    def _ordered_recent_events(self, timeline: Timeline) -> list[dict[str, Any]]:
        recent = timeline.events_within_window(self.WINDOW_MINUTES)
        indexed = list(enumerate(recent))
        return [
            event
            for _, event in sorted(
                indexed,
                key=lambda item: (
                    1 if self._event_time(item[1]) is None else 0,
                    self._event_time(item[1]) or datetime.min,
                    item[0],
                ),
            )
        ]

    def _message(self, event: dict[str, Any]) -> str:
        return str(event.get("message") or "")

    def _reason(self, event: dict[str, Any]) -> str:
        return str(event.get("reason") or "")

    def _source_component(self, event: dict[str, Any]) -> str:
        source = event.get("source")
        if isinstance(source, dict):
            return str(source.get("component") or "")
        return str(source or "")

    def _occurrences(self, event: dict[str, Any]) -> int:
        try:
            return max(1, int(event.get("count", 1)))
        except Exception:
            return 1

    def _pod_key(self, pod: dict[str, Any]) -> tuple[str, str]:
        metadata = pod.get("metadata", {}) or {}
        return (
            str(metadata.get("namespace") or "default"),
            str(metadata.get("name") or ""),
        )

    def _event_involves_pod(self, event: dict[str, Any], pod: dict[str, Any]) -> bool:
        involved = event.get("involvedObject")
        if not isinstance(involved, dict):
            return False
        namespace, pod_name = self._pod_key(pod)
        kind = str(involved.get("kind") or "").lower()
        if kind and kind != "pod":
            return False
        if pod_name and involved.get("name") and involved.get("name") != pod_name:
            return False
        if (
            namespace
            and involved.get("namespace")
            and involved.get("namespace") != namespace
        ):
            return False
        return True

    def _object_name(self, obj: dict[str, Any], fallback: str) -> str:
        return str(obj.get("metadata", {}).get("name") or fallback)

    def _object_namespace(self, obj: dict[str, Any]) -> str:
        return str(obj.get("metadata", {}).get("namespace") or "default")

    def _collect_secret_refs(self, pod: dict[str, Any]) -> dict[str, list[str]]:
        refs: dict[str, list[str]] = {}
        spec = pod.get("spec", {}) or {}

        def add(name: str | None, surface: str, optional: bool = False) -> None:
            if optional or not name:
                return
            refs.setdefault(str(name), [])
            if surface not in refs[str(name)]:
                refs[str(name)].append(surface)

        for volume in spec.get("volumes", []) or []:
            volume_name = str(volume.get("name") or "<volume>")
            secret = volume.get("secret") or {}
            add(
                secret.get("secretName"),
                f"Referenced by secret volume '{volume_name}'",
                bool(secret.get("optional")),
            )

            projected = volume.get("projected") or {}
            for source in projected.get("sources", []) or []:
                projected_secret = source.get("secret") or {}
                add(
                    projected_secret.get("name"),
                    f"Referenced by projected volume '{volume_name}'",
                    bool(projected_secret.get("optional")),
                )

        for container_group in ("initContainers", "containers", "ephemeralContainers"):
            for container in spec.get(container_group, []) or []:
                container_name = str(container.get("name") or "<container>")
                for env in container.get("env", []) or []:
                    secret_ref = (env.get("valueFrom") or {}).get("secretKeyRef") or {}
                    add(
                        secret_ref.get("name"),
                        f"Referenced by env '{env.get('name', '<env>')}' in container '{container_name}'",
                        bool(secret_ref.get("optional")),
                    )
                for env_from in container.get("envFrom", []) or []:
                    secret_ref = env_from.get("secretRef") or {}
                    add(
                        secret_ref.get("name"),
                        f"Referenced by envFrom in container '{container_name}'",
                        bool(secret_ref.get("optional")),
                    )

        return refs

    def _collect_secret_provider_classes(
        self, pod: dict[str, Any]
    ) -> dict[str, list[str]]:
        refs: dict[str, list[str]] = {}
        for volume in (pod.get("spec", {}) or {}).get("volumes", []) or []:
            csi = volume.get("csi") or {}
            if csi.get("driver") != "secrets-store.csi.k8s.io":
                continue
            attrs = csi.get("volumeAttributes", {}) or {}
            spc_name = attrs.get("secretProviderClass")
            if not spc_name:
                continue
            refs.setdefault(str(spc_name), [])
            refs[str(spc_name)].append(
                f"Referenced by Secrets Store CSI volume '{volume.get('name', '<volume>')}'"
            )
        return refs

    def _pod_references_external_secret(
        self,
        pod: dict[str, Any],
        target_secret_names: set[str],
        spc_names: set[str],
    ) -> bool:
        pod_secret_refs = self._collect_secret_refs(pod)
        pod_spc_refs = self._collect_secret_provider_classes(pod)
        return bool(target_secret_names & set(pod_secret_refs)) or bool(
            spc_names & set(pod_spc_refs)
        )

    def _condition_text(self, obj: dict[str, Any]) -> str:
        bits: list[str] = []
        for condition in obj.get("status", {}).get("conditions", []) or []:
            if not isinstance(condition, dict):
                continue
            bits.append(
                " ".join(
                    str(condition.get(key) or "")
                    for key in ("type", "status", "reason", "message")
                )
            )
        return " ".join(bits).lower()

    def _object_failure_detail(self, obj: dict[str, Any]) -> str | None:
        text = " ".join(
            [
                self._condition_text(obj),
                str(obj.get("status", {}) or {}),
            ]
        ).lower()
        if not text:
            return None
        if not any(marker in text for marker in self.SYNC_FAILURE_MARKERS):
            return None

        for condition in obj.get("status", {}).get("conditions", []) or []:
            if not isinstance(condition, dict):
                continue
            status = str(condition.get("status") or "")
            reason = str(condition.get("reason") or "")
            message = str(condition.get("message") or "")
            combined = f"{reason} {message}".lower()
            if status == "False" or any(
                marker in combined for marker in self.SYNC_FAILURE_MARKERS
            ):
                return f"{condition.get('type', 'Condition')}={status} reason={reason}: {message}".strip(
                    ": "
                )
        return "External secret object reports sync/provider failure"

    def _external_object_signals(
        self,
        context: dict[str, Any],
        namespace: str,
    ) -> dict[str, Any]:
        objects = context.get("objects", {}) or {}
        signals: list[str] = []
        object_evidence: dict[str, list[str]] = {}
        target_secret_names: set[str] = set()
        spc_names: set[str] = set()
        external_names: set[str] = set()

        for fallback, obj in (objects.get("externalsecret", {}) or {}).items():
            if not isinstance(obj, dict):
                continue
            if self._object_namespace(obj) != namespace:
                continue
            name = self._object_name(obj, str(fallback))
            external_names.add(name)
            target = obj.get("spec", {}).get("target", {}) or {}
            target_name = target.get("name") or name
            target_secret_names.add(str(target_name))
            detail = self._object_failure_detail(obj)
            if detail:
                signals.append(f"ExternalSecret '{name}' reports {detail}")
                object_evidence[f"externalsecret:{name}"] = [detail]

        for kind in ("secretstore", "clustersecretstore"):
            for fallback, obj in (objects.get(kind, {}) or {}).items():
                if not isinstance(obj, dict):
                    continue
                if kind == "secretstore" and self._object_namespace(obj) != namespace:
                    continue
                name = self._object_name(obj, str(fallback))
                external_names.add(name)
                detail = self._object_failure_detail(obj)
                if detail:
                    signals.append(f"{kind.title()} '{name}' reports {detail}")
                    object_evidence[f"{kind}:{name}"] = [detail]

        for fallback, obj in (objects.get("secretproviderclass", {}) or {}).items():
            if not isinstance(obj, dict):
                continue
            if self._object_namespace(obj) != namespace:
                continue
            name = self._object_name(obj, str(fallback))
            spc_names.add(name)
            external_names.add(name)
            for entry in obj.get("spec", {}).get("secretObjects", []) or []:
                if isinstance(entry, dict) and entry.get("secretName"):
                    target_secret_names.add(str(entry["secretName"]))

        for fallback, obj in (
            objects.get("secretproviderclasspodstatus", {}) or {}
        ).items():
            if not isinstance(obj, dict):
                continue
            if self._object_namespace(obj) != namespace:
                continue
            name = self._object_name(obj, str(fallback))
            spc_name = str(obj.get("status", {}).get("secretProviderClassName") or name)
            spc_names.add(spc_name)
            external_names.add(spc_name)
            detail = self._object_failure_detail(obj)
            if detail:
                signals.append(
                    f"SecretProviderClassPodStatus '{name}' reports {detail}"
                )
                object_evidence[f"secretproviderclasspodstatus:{name}"] = [detail]

        return {
            "signals": signals,
            "object_evidence": object_evidence,
            "target_secret_names": target_secret_names,
            "spc_names": spc_names,
            "external_names": external_names,
        }

    def _is_external_sync_event(
        self,
        event: dict[str, Any],
        target_names: set[str],
        external_names: set[str],
    ) -> bool:
        text = " ".join(
            [self._reason(event), self._message(event), self._source_component(event)]
        ).lower()
        if not any(marker in text for marker in self.EXTERNAL_SECRET_EVENT_MARKERS):
            return False
        if not any(marker in text for marker in self.SYNC_FAILURE_MARKERS):
            return False
        if not target_names and not external_names:
            return True
        return any(name.lower() in text for name in target_names | external_names)

    def _extract_secret_from_pod_failure(self, message: str) -> str | None:
        for pattern in (self.SECRET_NOT_FOUND_RE, self.SECRET_KEY_RE):
            match = pattern.search(message)
            if match:
                return str(match.group(match.lastindex or 1))
        return None

    def _is_pod_secret_failure(
        self,
        event: dict[str, Any],
        pod: dict[str, Any],
        target_secret_names: set[str],
        spc_names: set[str],
    ) -> bool:
        if not self._event_involves_pod(event, pod):
            return False
        reason = self._reason(event)
        message = self._message(event)
        text = f"{reason} {message}".lower()
        if not any(marker in text for marker in self.POD_SECRET_FAILURE_MARKERS):
            return False

        extracted_secret = self._extract_secret_from_pod_failure(message)
        if extracted_secret and target_secret_names:
            return extracted_secret in target_secret_names
        if any(name.lower() in text for name in target_secret_names | spc_names):
            return True
        if self.NONEXISTENT_SECRET_KEY_RE.search(message) and target_secret_names:
            return True
        return False

    def _status_waiting_config_error(self, pod: dict[str, Any]) -> tuple[bool, str]:
        for status in pod.get("status", {}).get("containerStatuses", []) or []:
            state = status.get("state", {}) or {}
            waiting = state.get("waiting", {}) or {}
            reason = str(waiting.get("reason") or "")
            if reason in {"CreateContainerConfigError", "ContainerCreating"}:
                return True, str(status.get("name") or "<container>")
        return False, "<container>"

    def _candidate(
        self,
        pod: dict[str, Any],
        events: list[dict[str, Any]],
        context: dict[str, Any],
    ) -> dict[str, Any] | None:
        timeline = context.get("timeline")
        if not isinstance(timeline, Timeline):
            return None

        namespace, pod_name = self._pod_key(pod)
        object_signals = self._external_object_signals(context, namespace)
        target_secret_names = set(object_signals["target_secret_names"])
        spc_names = set(object_signals["spc_names"])
        external_names = set(object_signals["external_names"])
        pod_secret_refs = self._collect_secret_refs(pod)
        pod_spc_refs = self._collect_secret_provider_classes(pod)

        # In event-only captures the ExternalSecret/SecretProviderClass object may
        # be absent, so use the Pod's own references as candidate names and let
        # the timeline event prove the external provider relationship.
        if not target_secret_names:
            target_secret_names.update(pod_secret_refs)
        if not spc_names:
            spc_names.update(pod_spc_refs)

        if not self._pod_references_external_secret(
            pod, target_secret_names, spc_names
        ):
            return None

        ordered = self._ordered_recent_events(timeline)
        sync_events = [
            event
            for event in ordered
            if self._is_external_sync_event(
                event,
                target_secret_names | spc_names,
                external_names,
            )
        ]
        pod_failures = [
            event
            for event in ordered
            if self._is_pod_secret_failure(
                event,
                pod,
                target_secret_names,
                spc_names,
            )
        ]

        if not sync_events and not object_signals["signals"]:
            return None
        if not pod_failures:
            waiting, _container_name = self._status_waiting_config_error(pod)
            if not waiting:
                return None

        sequences: list[tuple[dict[str, Any], dict[str, Any]]] = []
        for sync_event in sync_events:
            sync_end = self._event_end(sync_event) or self._event_time(sync_event)
            if sync_end is None:
                continue
            for pod_event in pod_failures:
                pod_time = self._event_time(pod_event)
                if pod_time is None or pod_time < sync_end:
                    continue
                if pod_time - sync_end > self.MAX_SYNC_TO_POD_GAP:
                    break
                sequences.append((sync_event, pod_event))
                break

        if sync_events and pod_failures and not sequences:
            return None

        sync_occurrences = sum(self._occurrences(event) for event in sync_events)
        if sync_events and sync_occurrences < self.MIN_SYNC_FAILURE_OCCURRENCES:
            return None

        waiting_config_error, container_name = self._status_waiting_config_error(pod)
        representative_sync = (
            max(
                sync_events,
                key=lambda event: (self._occurrences(event), self._message(event)),
            )
            if sync_events
            else None
        )
        representative_pod_failure = (
            max(
                pod_failures,
                key=lambda event: (self._occurrences(event), self._message(event)),
            )
            if pod_failures
            else None
        )
        duration_seconds = timeline.duration_between(
            lambda event: self._is_external_sync_event(
                event,
                target_secret_names | spc_names,
                external_names,
            )
        )

        return {
            "pod_name": pod_name,
            "namespace": namespace,
            "container_name": container_name,
            "target_secret_names": sorted(target_secret_names),
            "spc_names": sorted(spc_names),
            "external_names": sorted(external_names),
            "sync_occurrences": sync_occurrences,
            "representative_sync_message": (
                self._message(representative_sync).strip()
                if representative_sync
                else object_signals["signals"][0]
            ),
            "representative_pod_failure_message": (
                self._message(representative_pod_failure).strip()
                if representative_pod_failure
                else ""
            ),
            "object_signal_evidence": object_signals["signals"],
            "object_evidence": object_signals["object_evidence"],
            "sequence_count": len(sequences),
            "pod_failure_count": len(pod_failures),
            "waiting_config_error": waiting_config_error,
            "duration_seconds": max(0.0, duration_seconds),
        }

    def matches(self, pod, events, context) -> bool:
        candidate = self._candidate(pod, events, context)
        if candidate is None:
            context.pop(self.CACHE_KEY, None)
            return False
        context[self.CACHE_KEY] = candidate
        return True

    def explain(self, pod, events, context):
        candidate = context.get(self.CACHE_KEY) or self._candidate(pod, events, context)
        if candidate is None:
            raise ValueError(
                "ExternalSecretsSyncFailure explain() called without match"
            )

        pod_name = candidate["pod_name"]
        namespace = candidate["namespace"]
        target_display = (
            ", ".join(candidate["target_secret_names"])
            or ", ".join(candidate["spc_names"])
            or "external secret"
        )
        external_display = (
            ", ".join(candidate["external_names"]) or "external secret provider"
        )

        evidence = [
            f"Pod {namespace}/{pod_name} depends on externally synchronized secret material: {target_display}",
            f"External secret provider/controller failure is associated with {external_display}",
            f"Representative external sync failure: {candidate['representative_sync_message']}",
        ]
        if candidate["sync_occurrences"]:
            evidence.append(
                f"Observed {candidate['sync_occurrences']} external secret sync failure occurrence(s) within {self.WINDOW_MINUTES} minutes"
            )
        if candidate["representative_pod_failure_message"]:
            evidence.append(
                f"Representative pod startup symptom: {candidate['representative_pod_failure_message']}"
            )
        if candidate["sequence_count"]:
            evidence.append(
                f"Timeline links external secret sync failure to pod secret/mount failure in {candidate['sequence_count']} sequence(s)"
            )
        if candidate["waiting_config_error"]:
            evidence.append(
                f"Container '{candidate['container_name']}' is waiting on secret-backed configuration"
            )
        if candidate["duration_seconds"] > 0:
            evidence.append(
                f"External secret sync failures persisted for {candidate['duration_seconds'] / 60.0:.1f} minutes"
            )
        evidence.extend(candidate["object_signal_evidence"])

        object_evidence = {
            f"pod:{pod_name}": [
                "Pod startup depends on secret material produced by an external secret integration"
            ],
            "timeline:external_secret_sync": [
                "External provider/controller failure occurred before or during the pod secret dependency failure"
            ],
        }
        for secret_name in candidate["target_secret_names"]:
            object_evidence[f"secret:{secret_name}"] = [
                "Kubernetes Secret is generated from an external secret source and is unavailable or incomplete"
            ]
        for spc_name in candidate["spc_names"]:
            object_evidence[f"secretproviderclass:{spc_name}"] = [
                "Secrets Store CSI provider class is part of the failing secret mount/sync path"
            ]
        for key, items in candidate["object_evidence"].items():
            object_evidence.setdefault(key, []).extend(items)

        chain = CausalChain(
            causes=[
                Cause(
                    code="WORKLOAD_DEPENDS_ON_EXTERNAL_SECRET",
                    message=f"Pod references secret material supplied by {external_display}",
                    role="configuration_context",
                ),
                Cause(
                    code="EXTERNAL_SECRET_SYNC_FAILED",
                    message="External Secrets, Vault, or Secrets Store CSI failed to fetch or publish required secret data",
                    role="configuration_root",
                    blocking=True,
                ),
                Cause(
                    code="KUBERNETES_SECRET_UNAVAILABLE",
                    message="The Kubernetes Secret or mounted secret data is missing or incomplete for kubelet startup",
                    role="configuration_intermediate",
                ),
                Cause(
                    code="POD_STARTUP_BLOCKED_BY_SECRET_DEPENDENCY",
                    message="Pod startup is blocked because required secret-backed configuration cannot be resolved",
                    role="workload_symptom",
                ),
            ]
        )

        return {
            "root_cause": "External secret sync failed before required secret material was available",
            "confidence": 0.97,
            "blocking": True,
            "causes": chain,
            "evidence": evidence,
            "object_evidence": object_evidence,
            "likely_causes": [
                "External Secrets Operator cannot read the configured SecretStore or remote secret",
                "Vault, cloud secret manager, or provider credentials are denied, expired, or throttled",
                "Secrets Store CSI driver or provider failed to mount or sync secret objects",
                "The ExternalSecret target Secret or key has not been created before the Pod starts",
            ],
            "suggested_checks": [
                f"kubectl describe pod {pod_name} -n {namespace}",
                "kubectl get externalsecret,secretstore,clustersecretstore -A",
                "kubectl describe externalsecret <name> -n <namespace>",
                "kubectl describe secretproviderclass <name> -n <namespace>",
                "Inspect external-secrets, secrets-store-csi-driver, and provider/Vault controller logs for auth or provider errors",
            ],
        }
